name: Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
# For scheduled deployment with Cron Jobs.
## Examples of cron schedule expressions:
### '0 * * * *': hourly
### '0 0 * * *': daily
### '0 0 1 * *': monthly

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: reposense/reposense-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Required
          version: 'release' # Optional | Default: release | Other: master/tag v1.6.1/etc
          configDirectory: 'configs' # Optional | Default: configs
          service: 'gh-pages' # Optional | Default: gh-pages | Other: surge
          cliArgs: '--since d1' # Optional | Default: ''
      - uses: reposense/reposense-action@main
        with:
          token: ${{ secrets.SURGE_TOKEN }} # Required
          version: 'release' # Optional | Default: release | Other: master/tag v1.6.1/etc
          configDirectory: 'configs' # Optional | Default: configs
          service: 'surge'
          domain: 'reposense-action.surge.sh'
          cliArgs: '--since d1' # Optional | Default: ''
